language: go
sudo: required
dist: precise
go:
  - 1.8.5
  - 1.9.2
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
env:
  - PROPER_PATH=gopath/src/github.com/gohugoio/hugo
install:
  - mkdir -p $HOME/$PROPER_PATH
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/${PROPER_PATH}/
  - export TRAVIS_BUILD_DIR=$HOME/$PROPER_PATH
  - cd $TRAVIS_BUILD_DIR
  - go get github.com/magefile/mage
  - mage vendor
script:
  - mage hugoRace
  - mage -v check
  - ./hugo -s docs/
  - ./hugo --renderToMemory -s docs/
before_install:
  # gem install must be run with sudo on OSX
  - sudo gem install asciidoctor | gem install asciidoctor
